_target_: research.dataset.adni.AdniDataset
dataset_cfg:
  _target_: research.common.dataset_config.DatasetConfig
  task: 
    _target_: '${get_method: research.common.dataset_config.DatasetTask.__getattr__}'
    name: PREDICTION
  mode:
    _target_: '${get_method: research.common.dataset_config.DataMode.__getattr__}'
    name: SCANS
  split_type:
    _target_: research.common.dataset_config.NestedCV
    num_inner_fold: 3
    num_outer_fold: 5
  scan_paths: "/media/rohan/ThirdHardDrive/Research/Combined_FSL/scans"
  embedding_paths: "/home/rohan/Documents/main_embeddings_254"

  batch_size: 8
  # cohorts: 
  ni_vars:
    - "MMSE"
    - "CDRSB"
    - "mPACCtrailsB"
    - "mPACCdigit"
    - "APOE4"
    - "ADAS11"
    - "ADAS13"
    - "ADASQ4"
    - "FAQ"
    - "RAVLT_forgetting"
    - "RAVLT_immediate"
    - "RAVLT_learning"
    - "TRABSCOR"

  load_embeddings: True
  num_seq_visits: 3
  seq_visit_delta: 6
  progression_window: 48
  tolerance_lower: 24
  tolerance_upper: 0