_target_: research.dataset.adni.AdniDataset
dataset_cfg:
  _target_: research.common.dataset_config.DatasetConfig
  task: 
    _target_: '${get_method: research.common.dataset_config.DatasetTask.__getattr__}'
    name: PREDICTION
  mode:
    _target_: '${get_method: research.common.dataset_config.DataMode.__getattr__}'
    name: PATHS
  split_type:
    # _target_: research.common.dataset_config.NestedCV
    # num_inner_fold: 3
    # num_outer_fold: 5
    _target_: research.common.dataset_config.BasicSplit
    train_ratio: 0.8
    val_ratio: 0.0
    test_ratio: 0.2
  scan_paths: "/media/rohan/ThirdHardDrive/Research/Combined_FSL/scans"
  embedding_paths: "/media/rohan/ThirdHardDrive/Research/Combined_FSL/embeddings"

  batch_size: 1
  ni_vars:
    -
      name: "MMSE"
      type: continuous_bounded
      min: 0
      max: 30
    - 
      name: "CDRSB"
      type: continuous_bounded
      min: 0
      max: 30
    - 
      name: "mPACCtrailsB"
      type: normal
    -
      name: "mPACCdigit"
      type: normal
    - 
      name: "APOE4"
      type: discrete
      num_classes: 3
    -
      name: "ADAS11"
      type: continuous_bounded
      min: 0
      max: 70
    -
      name: "ADAS13"
      type: continuous_bounded
      min: 0
      max: 85
    - 
      name: "ADASQ4"
      type: continuous_bounded
      min: 0
      max: 10
    - 
      name: "FAQ"
      type: continuous_bounded
      min: 0
      max: 30
    - 
      name: "RAVLT_immediate"
      type: continuous_bounded
      min: 0
      max: 75
    - 
      name: "RAVLT_learning"
      type: continuous_bounded
      min: -15
      max: 15
    - 
      name: "TRABSCOR"
      type: continuous_bounded
      min: 0
      max: 1000

  load_embeddings: False
  num_seq_visits: 3
  seq_visit_delta: 6
  progression_window: 36
  tolerance_lower: 24
  tolerance_upper: 12