_target_: research.tasks.embeddings.EmbeddingTask

defaults:
  - _self_
  - model: densenet


dataset:
  _target_: research.dataset.adni.AdniDataset
  dataset_cfg:
    _target_: research.common.dataset_config.DatasetConfig
    task: 
      _target_: '${get_method: research.common.dataset_config.DatasetTask.__getattr__}'
      name: PREDICTION
    mode:
      _target_: '${get_method: research.common.dataset_config.DataMode.__getattr__}'
      name: PATHS
    split_type:
      _target_: research.common.dataset_config.NoSplit
    scan_paths: "/media/rohan/ThirdHardDrive/Research/Combined_FSL/scans"
    embedding_paths: "/media/rohan/ThirdHardDrive/Research/Combined_FSL/embeddings"

    batch_size: 8
    # cohorts: 
    ni_vars:
      - "MMSE"
      - "CDRSB"
      - "mPACCtrailsB"
      - "mPACCdigit"
      - "APOE4"
      - "ADAS11"
      - "ADAS13"
      - "ADASQ4"
      - "FAQ"
      - "RAVLT_forgetting"
      - "RAVLT_immediate"
      - "RAVLT_learning"
      - "TRABSCOR"

    load_embeddings: False
    num_seq_visits: 3
    seq_visit_delta: 6
    progression_window: 48
    tolerance_lower: 24
    tolerance_upper: 0

embedding_cfg:
  _target_: research.common.config_classes.EmbeddingConfig
  scan_path: "/media/rohan/ThirdHardDrive/Research/Combined_FSL/scans"
  embedding_path: "/home/rohan/Documents/main_embeddings"
  weight_path: "/home/rohan/projects/Alzheimers-Research/saved_results/best_2class/checkpoints/163.pt"

  model_cls:
    _target_: hydra.utils.get_class
    path: research.models.densenet.DenseNet