_target_: research.tasks.train.TrainTask

defaults:
  - _self_
  - dataset: adni_prediction

train_cfg:
  _target_: research.common.config_classes.TrainConfig
  model_cls:
    _target_: hydra.utils.get_class
    path: research.models.miniconv.ImageOnly
  optim:
    _target_: functools.partial
    _args_: ['${get_method: torch.optim.SGD}']
    lr: 1e-4
    momentum: 0.9
  loss_function:
    _target_: torch.nn.CrossEntropyLoss
  num_epochs: 2500

model: